name: KMA
main: com.posi.KMA.KMA
version: 0.1

commands: 
  createmission:
    usage: /createmission [name] [cost] [money-reward] [xp-reward] [respect-reward] [typ:headhunter,stealth,main,protect]
   
  setmobspawn:
    usage: /setmobspawn [mission] [mob]