/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIWrapper */

#ifndef _Included_JNIWrapper
#define _Included_JNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIWrapper
 * Method:    loadMemory
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_JNIWrapper_loadMemory
  (JNIEnv *, jobject);

/*
 * Class:     JNIWrapper
 * Method:    configPortIO
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_JNIWrapper_configPortIO
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JNIWrapper
 * Method:    configPortAlt
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_JNIWrapper_configPortAlt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JNIWrapper
 * Method:    writeOutput
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_JNIWrapper_writeOutput
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JNIWrapper
 * Method:    readInput
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JNIWrapper_readInput
  (JNIEnv *, jobject, jint);

/*
 * Class:     JNIWrapper
 * Method:    i2c_write_to_slave
 * Signature: (CC)V
 */
JNIEXPORT void JNICALL Java_JNIWrapper_i2c_1write_1to_1slave
  (JNIEnv *, jobject, jchar, jchar);

/*
 * Class:     JNIWrapper
 * Method:    i2c_read_from_slave
 * Signature: (CC)V
 */
JNIEXPORT void JNICALL Java_JNIWrapper_i2c_1read_1from_1slave
  (JNIEnv *, jobject, jchar, jchar);

/*
 * Class:     JNIWrapper
 * Method:    pic_response
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_JNIWrapper_pic_1response
  (JNIEnv *, jobject);

/*
 * Class:     JNIWrapper
 * Method:    getADCValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JNIWrapper_getADCValue
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
